version: "3.9"

services:
  backend:
    image: angad696/cockpit_backend:latest
    container_name: cockpit_backend
    ports:
      - "5001:5001"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./backend/logs:/app/logs
    restart: always

  frontend:
    image: angad696/cockpit_frontend:latest
    container_name: cockpit_frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - backend
    restart: unless-stopped
